name: e_commerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  connectivity_plus: ^6.1.3
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_rating_bar: ^4.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_sign_in: ^6.2.2
  http: ^1.3.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  readmore: ^3.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: assets/logos/light_logo.png
  image_dark: assets/logos/dark_logo.png
  android: true
  ios: true
  web: false
  android_12: # Add Android 12 specific settings
    color: "#ffffff"
    color_dark: "#000000"
    image: assets/logos/light_logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/logos/dark_logo.png
    icon_background_color_dark: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding/
    - assets/icons/
    - assets/icons/brands/
    - assets/logos/
    - assets/icons/categories/
    - assets/images/sales/
    - assets/images/products/
    - assets/images/payment_methods/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
